name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cs:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - name: "Git: checkout"
        uses: actions/checkout@v4

      - name: "PHP: setup 8.3"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: php-cs-fixer

      - name: "Composer: validate"
        run: composer validate --strict

      - name: "Composer: install"
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: "Php-CS-Fixer: version"
        run: vendor/bin/php-cs-fixer -V

      - name: "Php-CS-Fixer: check"
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

  sa:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "Git: checkout"
        uses: actions/checkout@v4

      - name: "PHP: setup 8.4"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: pcov
          tools: phpstan

      - name: "Composer: install"
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: "PHPStan: version"
        run: vendor/bin/phpstan --version

      - name: "PHPStan: analyze"
        run: vendor/bin/phpstan

  tests:
    name: "Tests (PHP ${{ matrix.php-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
      fail-fast: false
    steps:
      - name: "Git: checkout"
        uses: actions/checkout@v4

      - name: "PHP: setup ${{ matrix.php-version }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: phpunit

      - name: "Composer: install"
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: "PHPUnit: unit tests"
        run: vendor/bin/phpunit

      - name: "PHPUnit: all tests with coverage"
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: "Codecov: upload coverage"
        uses: codecov/codecov-action@v5
        if: matrix.php-version == '8.4'
        with:
          files: ./coverage.xml
